# Validate
ifeq ($(TEST_WATCHPOINTS),1)
ifeq ($(TEST_BREAKPOINTS),1)
$(error Breakpoints and watchpoints are exclusive in the current EDB implementation)
endif # TEST_BREAKPOINTS
endif # TEST_WATCHPOINTS

ifeq ($(TEST_INTERRUPT),1)
CFLAGS += -DTEST_INTERRUPT
endif # TEST_INTERRUPT

ifeq ($(TEST_WATCHPOINTS),1)
export CONFIG_ENABLE_WATCHPOINTS = 1
CFLAGS += -DTEST_WATCHPOINTS
endif # TEST_WATCHPOINTS

ifeq ($(TEST_BREAKPOINTS),1)
# Watchpoints and breakpoints are exclusive in current EDB impl
export CONFIG_ENABLE_WATCHPOINTS = 0
CFLAGS += -DTEST_BREAKPOINTS
endif # TEST_BREAKPOINTS
